SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

PROMPT Creating local phase 1 verification user...

ALTER SESSION SET CONTAINER = FREEPDB1;

SET DEFINE ON
SET VERIFY OFF
DEFINE phase1_password = '&1'

BEGIN
  EXECUTE IMMEDIATE 'DROP USER steam_course CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN
      RAISE;
    END IF;
END;
/

CREATE USER steam_course IDENTIFIED BY "&&phase1_password";
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE TO steam_course;
ALTER USER steam_course QUOTA UNLIMITED ON USERS;

UNDEFINE phase1_password
SET DEFINE OFF
SET VERIFY ON

PROMPT Local phase 1 verification user created.
