SET DEFINE OFF

PROMPT Creating Steam course database schema...

CREATE TABLE PLAYER (
  user_id VARCHAR2(32) NOT NULL,
  account VARCHAR2(50) NOT NULL,
  password_hash VARCHAR2(256) NOT NULL,
  nickname VARCHAR2(50) NOT NULL,
  credit_score NUMBER(3) DEFAULT 100 NOT NULL,
  status VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,
  version NUMBER(20) DEFAULT 0 NOT NULL,
  create_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  update_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PLAYER PRIMARY KEY (user_id),
  CONSTRAINT UK_PLAYER_ACCOUNT UNIQUE (account),
  CONSTRAINT CK_PLAYER_CREDIT CHECK (credit_score BETWEEN 0 AND 100),
  CONSTRAINT CK_PLAYER_STATUS CHECK (status IN ('NORMAL', 'FROZEN'))
);

CREATE TABLE DEVELOPER (
  dev_id VARCHAR2(32) NOT NULL,
  company_name VARCHAR2(100) NOT NULL,
  tax_id VARCHAR2(50) NOT NULL,
  contact_email VARCHAR2(100) NOT NULL,
  status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  join_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_DEVELOPER PRIMARY KEY (dev_id),
  CONSTRAINT UK_DEVELOPER_TAX_ID UNIQUE (tax_id),
  CONSTRAINT CK_DEVELOPER_STATUS CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE ADMIN_USER (
  admin_id VARCHAR2(32) NOT NULL,
  account VARCHAR2(50) NOT NULL,
  password_hash VARCHAR2(256) NOT NULL,
  role VARCHAR2(50) NOT NULL,
  create_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ADMIN_USER PRIMARY KEY (admin_id),
  CONSTRAINT UK_ADMIN_ACCOUNT UNIQUE (account),
  CONSTRAINT CK_ADMIN_ROLE CHECK (role IN ('SUPER_ADMIN', 'AUDITOR', 'RISK_ADMIN', 'CUSTOMER_SERVICE'))
);

CREATE TABLE WALLET_ACCOUNT (
  wallet_id VARCHAR2(32) NOT NULL,
  user_id VARCHAR2(32) NOT NULL,
  available_balance NUMBER(10,2) DEFAULT 0.00 NOT NULL,
  frozen_balance NUMBER(10,2) DEFAULT 0.00 NOT NULL,
  version NUMBER(20) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_WALLET_ACCOUNT PRIMARY KEY (wallet_id),
  CONSTRAINT UK_WALLET_USER UNIQUE (user_id),
  CONSTRAINT FK_WALLET_PLAYER FOREIGN KEY (user_id) REFERENCES PLAYER(user_id),
  CONSTRAINT CK_WALLET_AVAIL CHECK (available_balance >= 0),
  CONSTRAINT CK_WALLET_FROZEN CHECK (frozen_balance >= 0)
);

CREATE TABLE SYS_NOTICE (
  notice_id VARCHAR2(32) NOT NULL,
  publisher_type VARCHAR2(20) NOT NULL,
  publisher_id VARCHAR2(32),
  title VARCHAR2(200) NOT NULL,
  content CLOB NOT NULL,
  priority NUMBER(1) DEFAULT 0 NOT NULL,
  status VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
  publish_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  expire_time TIMESTAMP,
  CONSTRAINT PK_SYS_NOTICE PRIMARY KEY (notice_id),
  CONSTRAINT CK_NOTICE_PUBLISHER CHECK (publisher_type IN ('SYSTEM', 'ADMIN', 'DEVELOPER')),
  CONSTRAINT CK_NOTICE_PRIORITY CHECK (priority BETWEEN 0 AND 9),
  CONSTRAINT CK_NOTICE_STATUS CHECK (status IN ('DRAFT', 'PUBLISHED', 'EXPIRED', 'REVOKED'))
);

CREATE TABLE GAME (
  game_id VARCHAR2(32) NOT NULL,
  dev_id VARCHAR2(32) NOT NULL,
  game_name VARCHAR2(100) NOT NULL,
  base_price NUMBER(10,2) NOT NULL,
  discount_rate NUMBER(3,2) DEFAULT 1.00 NOT NULL,
  release_date DATE NOT NULL,
  reputation VARCHAR2(20),
  status VARCHAR2(20) DEFAULT 'OFFLINE' NOT NULL,
  CONSTRAINT PK_GAME PRIMARY KEY (game_id),
  CONSTRAINT FK_GAME_DEVELOPER FOREIGN KEY (dev_id) REFERENCES DEVELOPER(dev_id),
  CONSTRAINT CK_GAME_PRICE CHECK (base_price >= 0),
  CONSTRAINT CK_GAME_DISCOUNT CHECK (discount_rate BETWEEN 0 AND 1),
  CONSTRAINT CK_GAME_STATUS CHECK (status IN ('ONLINE', 'OFFLINE')),
  CONSTRAINT CK_GAME_REPUTATION CHECK (reputation IS NULL OR reputation IN ('OVERWHELMINGLY_POSITIVE', 'VERY_POSITIVE', 'MOSTLY_POSITIVE', 'MIXED', 'NEGATIVE'))
);

CREATE TABLE GAME_ORDER (
  order_id VARCHAR2(32) NOT NULL,
  user_id VARCHAR2(32) NOT NULL,
  total_amount NUMBER(10,2) NOT NULL,
  order_type VARCHAR2(20) NOT NULL,
  order_status VARCHAR2(20) DEFAULT 'CREATED' NOT NULL,
  payment_status VARCHAR2(20) DEFAULT 'UNPAID' NOT NULL,
  idempotency_key VARCHAR2(64),
  expire_time TIMESTAMP NOT NULL,
  create_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_GAME_ORDER PRIMARY KEY (order_id),
  CONSTRAINT FK_ORDER_PLAYER FOREIGN KEY (user_id) REFERENCES PLAYER(user_id),
  CONSTRAINT UK_ORDER_IDEMPOTENCY UNIQUE (idempotency_key),
  CONSTRAINT CK_ORDER_AMOUNT CHECK (total_amount >= 0),
  CONSTRAINT CK_ORDER_TYPE CHECK (order_type IN ('BUY_GAME', 'RECHARGE')),
  CONSTRAINT CK_ORDER_STATUS CHECK (order_status IN ('CREATED', 'CLOSED', 'COMPLETED', 'REFUNDING')),
  CONSTRAINT CK_ORDER_PAY_STATUS CHECK (payment_status IN ('UNPAID', 'PAID', 'PARTIAL_REFUNDED', 'REFUNDED'))
);

CREATE TABLE ORDER_DETAIL (
  detail_id VARCHAR2(32) NOT NULL,
  order_id VARCHAR2(32) NOT NULL,
  game_id VARCHAR2(32) NOT NULL,
  original_price NUMBER(10,2) NOT NULL,
  discount_amount NUMBER(10,2) NOT NULL,
  payable_amount NUMBER(10,2) NOT NULL,
  refund_amount NUMBER(10,2) DEFAULT 0.00 NOT NULL,
  CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (detail_id),
  CONSTRAINT FK_DETAIL_ORDER FOREIGN KEY (order_id) REFERENCES GAME_ORDER(order_id),
  CONSTRAINT FK_DETAIL_GAME FOREIGN KEY (game_id) REFERENCES GAME(game_id),
  CONSTRAINT UK_ORDER_GAME UNIQUE (order_id, game_id),
  CONSTRAINT CK_DETAIL_ORIG_PRICE CHECK (original_price >= 0),
  CONSTRAINT CK_DETAIL_DISCOUNT CHECK (discount_amount >= 0),
  CONSTRAINT CK_DETAIL_PAYABLE CHECK (payable_amount >= 0),
  CONSTRAINT CK_DETAIL_REFUND CHECK (refund_amount >= 0 AND refund_amount <= payable_amount)
);

CREATE TABLE ORDER_STATUS_LOG (
  log_id VARCHAR2(32) NOT NULL,
  order_id VARCHAR2(32) NOT NULL,
  from_status VARCHAR2(20),
  to_status VARCHAR2(20) NOT NULL,
  create_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ORDER_STATUS_LOG PRIMARY KEY (log_id),
  CONSTRAINT FK_ORDER_LOG_ORDER FOREIGN KEY (order_id) REFERENCES GAME_ORDER(order_id),
  CONSTRAINT CK_ORDER_LOG_TO CHECK (to_status IN ('CREATED', 'CLOSED', 'COMPLETED', 'REFUNDING')),
  CONSTRAINT CK_ORDER_LOG_FROM CHECK (from_status IS NULL OR from_status IN ('CREATED', 'CLOSED', 'COMPLETED', 'REFUNDING'))
);

CREATE TABLE PAYMENT_TRANSACTION (
  payment_id VARCHAR2(32) NOT NULL,
  order_id VARCHAR2(32) NOT NULL,
  provider_trade_no VARCHAR2(64),
  amount NUMBER(10,2) NOT NULL,
  status VARCHAR2(20) NOT NULL,
  create_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PAYMENT_TXN PRIMARY KEY (payment_id),
  CONSTRAINT FK_PAYMENT_ORDER FOREIGN KEY (order_id) REFERENCES GAME_ORDER(order_id),
  CONSTRAINT UK_PAYMENT_PROVIDER_NO UNIQUE (provider_trade_no),
  CONSTRAINT CK_PAYMENT_AMOUNT CHECK (amount >= 0),
  CONSTRAINT CK_PAYMENT_STATUS CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED'))
);

CREATE TABLE REFUND_TICKET (
  refund_id VARCHAR2(32) NOT NULL,
  order_id VARCHAR2(32) NOT NULL,
  refund_amount NUMBER(10,2) NOT NULL,
  refund_type VARCHAR2(20) NOT NULL,
  reason VARCHAR2(500) NOT NULL,
  play_time_hours NUMBER(5,2) NOT NULL,
  status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  apply_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_REFUND_TICKET PRIMARY KEY (refund_id),
  CONSTRAINT FK_REFUND_ORDER FOREIGN KEY (order_id) REFERENCES GAME_ORDER(order_id),
  CONSTRAINT CK_REFUND_AMOUNT CHECK (refund_amount > 0),
  CONSTRAINT CK_REFUND_TYPE CHECK (refund_type IN ('FULL', 'PARTIAL')),
  CONSTRAINT CK_REFUND_PLAYTIME CHECK (play_time_hours >= 0),
  CONSTRAINT CK_REFUND_STATUS CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE REFUND_DETAIL (
  refund_detail_id VARCHAR2(32) NOT NULL,
  refund_id VARCHAR2(32) NOT NULL,
  order_detail_id VARCHAR2(32) NOT NULL,
  refund_amount NUMBER(10,2) NOT NULL,
  CONSTRAINT PK_REFUND_DETAIL PRIMARY KEY (refund_detail_id),
  CONSTRAINT FK_REF_DETAIL_TICKET FOREIGN KEY (refund_id) REFERENCES REFUND_TICKET(refund_id),
  CONSTRAINT FK_REF_DETAIL_ORDER_DETAIL FOREIGN KEY (order_detail_id) REFERENCES ORDER_DETAIL(detail_id),
  CONSTRAINT CK_REF_DETAIL_AMOUNT CHECK (refund_amount > 0)
);

CREATE TABLE REFUND_AUDIT_LOG (
  audit_id VARCHAR2(32) NOT NULL,
  refund_id VARCHAR2(32) NOT NULL,
  operator_id VARCHAR2(32) NOT NULL,
  from_status VARCHAR2(20),
  to_status VARCHAR2(20) NOT NULL,
  reason VARCHAR2(500),
  create_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_REFUND_AUDIT_LOG PRIMARY KEY (audit_id),
  CONSTRAINT FK_REF_AUDIT_TICKET FOREIGN KEY (refund_id) REFERENCES REFUND_TICKET(refund_id),
  CONSTRAINT FK_REF_AUDIT_ADMIN FOREIGN KEY (operator_id) REFERENCES ADMIN_USER(admin_id),
  CONSTRAINT CK_REF_AUDIT_FROM CHECK (from_status IS NULL OR from_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELED')),
  CONSTRAINT CK_REF_AUDIT_TO CHECK (to_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE PLAYER_LIBRARY (
  lib_id VARCHAR2(32) NOT NULL,
  user_id VARCHAR2(32) NOT NULL,
  game_id VARCHAR2(32) NOT NULL,
  acquire_way VARCHAR2(20) NOT NULL,
  status VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,
  play_minutes NUMBER(10) DEFAULT 0 NOT NULL,
  last_play_time TIMESTAMP,
  CONSTRAINT PK_PLAYER_LIBRARY PRIMARY KEY (lib_id),
  CONSTRAINT FK_LIBRARY_PLAYER FOREIGN KEY (user_id) REFERENCES PLAYER(user_id),
  CONSTRAINT FK_LIBRARY_GAME FOREIGN KEY (game_id) REFERENCES GAME(game_id),
  CONSTRAINT UK_LIBRARY_USER_GAME UNIQUE (user_id, game_id),
  CONSTRAINT CK_LIBRARY_ACQUIRE CHECK (acquire_way IN ('BUY', 'FREE', 'REDEEM', 'GIFT')),
  CONSTRAINT CK_LIBRARY_STATUS CHECK (status IN ('NORMAL', 'REVOKED', 'FROZEN')),
  CONSTRAINT CK_LIBRARY_PLAY_MIN CHECK (play_minutes >= 0)
);

CREATE TABLE CDKEY_BATCH (
  batch_id VARCHAR2(32) NOT NULL,
  game_id VARCHAR2(32) NOT NULL,
  batch_no VARCHAR2(64) NOT NULL,
  valid_from TIMESTAMP NOT NULL,
  expire_time TIMESTAMP NOT NULL,
  CONSTRAINT PK_CDKEY_BATCH PRIMARY KEY (batch_id),
  CONSTRAINT FK_CDKEY_BATCH_GAME FOREIGN KEY (game_id) REFERENCES GAME(game_id),
  CONSTRAINT UK_CDKEY_BATCH_NO UNIQUE (batch_no),
  CONSTRAINT CK_CDKEY_BATCH_TIME CHECK (expire_time > valid_from)
);

CREATE TABLE CDKEY (
  cdkey_hash VARCHAR2(64) NOT NULL,
  batch_id VARCHAR2(32) NOT NULL,
  status VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
  generate_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_CDKEY PRIMARY KEY (cdkey_hash),
  CONSTRAINT FK_CDKEY_BATCH FOREIGN KEY (batch_id) REFERENCES CDKEY_BATCH(batch_id),
  CONSTRAINT CK_CDKEY_STATUS CHECK (status IN ('AVAILABLE', 'REDEEMED', 'REVOKED'))
);

CREATE TABLE CDKEY_REDEEM_LOG (
  log_id VARCHAR2(32) NOT NULL,
  user_id VARCHAR2(32) NOT NULL,
  submitted_hash VARCHAR2(64) NOT NULL,
  cdkey_hash VARCHAR2(64),
  result VARCHAR2(20) NOT NULL,
  fail_reason VARCHAR2(200),
  ip_hash VARCHAR2(128),
  create_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_CDKEY_REDEEM_LOG PRIMARY KEY (log_id),
  CONSTRAINT FK_REDEEM_PLAYER FOREIGN KEY (user_id) REFERENCES PLAYER(user_id),
  CONSTRAINT FK_REDEEM_CDKEY FOREIGN KEY (cdkey_hash) REFERENCES CDKEY(cdkey_hash),
  CONSTRAINT CK_REDEEM_RESULT CHECK (result IN ('SUCCESS', 'INVALID', 'EXPIRED', 'REDEEMED', 'BATCH_REVOKED'))
);

CREATE TABLE GAME_REVIEW (
  review_id VARCHAR2(32) NOT NULL,
  user_id VARCHAR2(32) NOT NULL,
  game_id VARCHAR2(32) NOT NULL,
  thumbs_up NUMBER(10) DEFAULT 0 NOT NULL,
  status VARCHAR2(20) DEFAULT 'VISIBLE' NOT NULL,
  create_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_GAME_REVIEW PRIMARY KEY (review_id),
  CONSTRAINT FK_REVIEW_PLAYER FOREIGN KEY (user_id) REFERENCES PLAYER(user_id),
  CONSTRAINT FK_REVIEW_GAME FOREIGN KEY (game_id) REFERENCES GAME(game_id),
  CONSTRAINT UK_REVIEW_USER_GAME UNIQUE (user_id, game_id),
  CONSTRAINT CK_REVIEW_THUMBS CHECK (thumbs_up >= 0),
  CONSTRAINT CK_REVIEW_STATUS CHECK (status IN ('VISIBLE', 'HIDDEN'))
);

CREATE TABLE REVIEW_VERSION (
  version_id VARCHAR2(32) NOT NULL,
  review_id VARCHAR2(32) NOT NULL,
  version_no NUMBER(5) NOT NULL,
  is_recommend NUMBER(1) NOT NULL,
  content CLOB NOT NULL,
  create_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_REVIEW_VERSION PRIMARY KEY (version_id),
  CONSTRAINT FK_REVIEW_VERSION_REVIEW FOREIGN KEY (review_id) REFERENCES GAME_REVIEW(review_id),
  CONSTRAINT UK_REVIEW_VERSION_NO UNIQUE (review_id, version_no),
  CONSTRAINT CK_REVIEW_VERSION_NO CHECK (version_no > 0),
  CONSTRAINT CK_REVIEW_RECOMMEND CHECK (is_recommend IN (0, 1))
);

CREATE TABLE ACHIEVEMENT (
  ach_id VARCHAR2(32) NOT NULL,
  game_id VARCHAR2(32) NOT NULL,
  ach_name VARCHAR2(100) NOT NULL,
  description VARCHAR2(500),
  global_rate NUMBER(5,2),
  CONSTRAINT PK_ACHIEVEMENT PRIMARY KEY (ach_id),
  CONSTRAINT FK_ACH_GAME FOREIGN KEY (game_id) REFERENCES GAME(game_id),
  CONSTRAINT CK_ACH_RATE CHECK (global_rate IS NULL OR global_rate BETWEEN 0 AND 100)
);

CREATE TABLE PLAYER_ACHIEVEMENT (
  unlock_id VARCHAR2(32) NOT NULL,
  user_id VARCHAR2(32) NOT NULL,
  ach_id VARCHAR2(32) NOT NULL,
  unlock_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PLAYER_ACHIEVEMENT PRIMARY KEY (unlock_id),
  CONSTRAINT FK_PLAYER_ACH_PLAYER FOREIGN KEY (user_id) REFERENCES PLAYER(user_id),
  CONSTRAINT FK_PLAYER_ACH_ACH FOREIGN KEY (ach_id) REFERENCES ACHIEVEMENT(ach_id),
  CONSTRAINT UK_PLAYER_ACH UNIQUE (user_id, ach_id)
);

CREATE TABLE ITEM_TEMPLATE (
  template_id VARCHAR2(32) NOT NULL,
  game_id VARCHAR2(32) NOT NULL,
  item_name VARCHAR2(100) NOT NULL,
  rarity VARCHAR2(20) NOT NULL,
  image_url VARCHAR2(255),
  CONSTRAINT PK_ITEM_TEMPLATE PRIMARY KEY (template_id),
  CONSTRAINT FK_ITEM_TEMPLATE_GAME FOREIGN KEY (game_id) REFERENCES GAME(game_id),
  CONSTRAINT CK_ITEM_RARITY CHECK (rarity IN ('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY'))
);

CREATE TABLE INVENTORY_ITEM (
  item_id VARCHAR2(32) NOT NULL,
  template_id VARCHAR2(32) NOT NULL,
  user_id VARCHAR2(32) NOT NULL,
  wear_rating NUMBER(5,4),
  status VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,
  acquire_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  version NUMBER(20) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_INVENTORY_ITEM PRIMARY KEY (item_id),
  CONSTRAINT FK_INV_ITEM_TEMPLATE FOREIGN KEY (template_id) REFERENCES ITEM_TEMPLATE(template_id),
  CONSTRAINT FK_INV_ITEM_PLAYER FOREIGN KEY (user_id) REFERENCES PLAYER(user_id),
  CONSTRAINT CK_INV_WEAR CHECK (wear_rating IS NULL OR wear_rating BETWEEN 0 AND 1),
  CONSTRAINT CK_INV_STATUS CHECK (status IN ('NORMAL', 'IN_MARKET', 'LOCKED', 'REVOKED'))
);

CREATE TABLE MARKET_ORDER (
  market_order_id VARCHAR2(32) NOT NULL,
  user_id VARCHAR2(32) NOT NULL,
  template_id VARCHAR2(32) NOT NULL,
  item_id VARCHAR2(32),
  order_type VARCHAR2(10) NOT NULL,
  target_price NUMBER(10,2) NOT NULL,
  frozen_amount NUMBER(10,2) DEFAULT 0.00 NOT NULL,
  status VARCHAR2(20) DEFAULT 'MATCHING' NOT NULL,
  create_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MARKET_ORDER PRIMARY KEY (market_order_id),
  CONSTRAINT FK_MARKET_ORDER_PLAYER FOREIGN KEY (user_id) REFERENCES PLAYER(user_id),
  CONSTRAINT FK_MARKET_ORDER_TEMPLATE FOREIGN KEY (template_id) REFERENCES ITEM_TEMPLATE(template_id),
  CONSTRAINT FK_MARKET_ORDER_ITEM FOREIGN KEY (item_id) REFERENCES INVENTORY_ITEM(item_id),
  CONSTRAINT CK_MARKET_ORDER_TYPE CHECK (order_type IN ('BUY', 'SELL')),
  CONSTRAINT CK_MARKET_ORDER_PRICE CHECK (target_price > 0),
  CONSTRAINT CK_MARKET_ORDER_FROZEN CHECK (frozen_amount >= 0),
  CONSTRAINT CK_MARKET_ORDER_STATUS CHECK (status IN ('MATCHING', 'TRADED', 'CANCELED', 'EXPIRED')),
  CONSTRAINT CK_MARKET_ORDER_ITEM CHECK (
    (order_type = 'BUY' AND item_id IS NULL) OR
    (order_type = 'SELL' AND item_id IS NOT NULL)
  ),
  CONSTRAINT CK_MARKET_BUY_FREEZE CHECK (
    order_type <> 'BUY' OR status <> 'MATCHING' OR frozen_amount >= target_price
  )
);

CREATE TABLE MARKET_TRADE (
  trade_id VARCHAR2(32) NOT NULL,
  buy_order_id VARCHAR2(32) NOT NULL,
  sell_order_id VARCHAR2(32) NOT NULL,
  template_id VARCHAR2(32) NOT NULL,
  item_id VARCHAR2(32) NOT NULL,
  buyer_id VARCHAR2(32) NOT NULL,
  seller_id VARCHAR2(32) NOT NULL,
  trade_price NUMBER(10,2) NOT NULL,
  platform_fee NUMBER(10,2) NOT NULL,
  currency VARCHAR2(10) NOT NULL,
  trade_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MARKET_TRADE PRIMARY KEY (trade_id),
  CONSTRAINT FK_TRADE_BUY_ORDER FOREIGN KEY (buy_order_id) REFERENCES MARKET_ORDER(market_order_id),
  CONSTRAINT FK_TRADE_SELL_ORDER FOREIGN KEY (sell_order_id) REFERENCES MARKET_ORDER(market_order_id),
  CONSTRAINT FK_TRADE_TEMPLATE FOREIGN KEY (template_id) REFERENCES ITEM_TEMPLATE(template_id),
  CONSTRAINT FK_TRADE_ITEM FOREIGN KEY (item_id) REFERENCES INVENTORY_ITEM(item_id),
  CONSTRAINT FK_TRADE_BUYER FOREIGN KEY (buyer_id) REFERENCES PLAYER(user_id),
  CONSTRAINT FK_TRADE_SELLER FOREIGN KEY (seller_id) REFERENCES PLAYER(user_id),
  CONSTRAINT CK_TRADE_PRICE CHECK (trade_price > 0),
  CONSTRAINT CK_TRADE_FEE CHECK (platform_fee >= 0),
  CONSTRAINT CK_TRADE_CURRENCY CHECK (currency IN ('CNY', 'USD'))
);

CREATE TABLE ITEM_TRANSFER_LEDGER (
  transfer_id VARCHAR2(32) NOT NULL,
  item_id VARCHAR2(32) NOT NULL,
  from_user_id VARCHAR2(32),
  to_user_id VARCHAR2(32) NOT NULL,
  transfer_type VARCHAR2(20) NOT NULL,
  transfer_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ITEM_TRANSFER_LEDGER PRIMARY KEY (transfer_id),
  CONSTRAINT FK_TRANSFER_ITEM FOREIGN KEY (item_id) REFERENCES INVENTORY_ITEM(item_id),
  CONSTRAINT FK_TRANSFER_FROM_PLAYER FOREIGN KEY (from_user_id) REFERENCES PLAYER(user_id),
  CONSTRAINT FK_TRANSFER_TO_PLAYER FOREIGN KEY (to_user_id) REFERENCES PLAYER(user_id),
  CONSTRAINT CK_TRANSFER_TYPE CHECK (transfer_type IN ('TRADE', 'DROP', 'ROLLBACK'))
);

CREATE TABLE WALLET_TRANSACTION (
  txn_id VARCHAR2(32) NOT NULL,
  wallet_id VARCHAR2(32) NOT NULL,
  biz_type VARCHAR2(20) NOT NULL,
  biz_ref_id VARCHAR2(32) NOT NULL,
  funds_direction VARCHAR2(20) NOT NULL,
  amount NUMBER(10,2) NOT NULL,
  avail_bal_before NUMBER(10,2) NOT NULL,
  avail_bal_after NUMBER(10,2) NOT NULL,
  idempotency_key VARCHAR2(64),
  create_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_WALLET_TRANSACTION PRIMARY KEY (txn_id),
  CONSTRAINT FK_WALLET_TXN_WALLET FOREIGN KEY (wallet_id) REFERENCES WALLET_ACCOUNT(wallet_id),
  CONSTRAINT UK_WALLET_TXN_IDEMP UNIQUE (idempotency_key),
  CONSTRAINT CK_WALLET_TXN_BIZ CHECK (biz_type IN ('RECHARGE', 'BUY_GAME', 'REFUND', 'MARKET_BUY', 'MARKET_SELL', 'MARKET_FREEZE', 'MARKET_UNFREEZE')),
  CONSTRAINT CK_WALLET_TXN_DIR CHECK (funds_direction IN ('DEBIT', 'CREDIT', 'FREEZE', 'UNFREEZE')),
  CONSTRAINT CK_WALLET_TXN_AMOUNT CHECK (amount > 0),
  CONSTRAINT CK_WALLET_TXN_BALANCE CHECK (avail_bal_before >= 0 AND avail_bal_after >= 0)
);

CREATE INDEX IDX_WALLET_TXN_WALLET_TIME ON WALLET_TRANSACTION(wallet_id, create_time);
CREATE INDEX IDX_WALLET_TXN_BIZ_REF ON WALLET_TRANSACTION(biz_type, biz_ref_id);
CREATE INDEX IDX_NOTICE_STATUS_TIME ON SYS_NOTICE(status, publish_time);
CREATE INDEX IDX_GAME_DEV_STATUS ON GAME(dev_id, status);
CREATE INDEX IDX_ORDER_USER_TIME ON GAME_ORDER(user_id, create_time);
CREATE INDEX IDX_ORDER_STATUS ON GAME_ORDER(order_status, payment_status);
CREATE INDEX IDX_DETAIL_ORDER ON ORDER_DETAIL(order_id);
CREATE INDEX IDX_ORDER_LOG_ORDER_TIME ON ORDER_STATUS_LOG(order_id, create_time);
CREATE INDEX IDX_PAYMENT_ORDER ON PAYMENT_TRANSACTION(order_id);
CREATE INDEX IDX_REFUND_ORDER_STATUS ON REFUND_TICKET(order_id, status);
CREATE INDEX IDX_REF_DETAIL_REFUND ON REFUND_DETAIL(refund_id);
CREATE INDEX IDX_REF_AUDIT_REFUND_TIME ON REFUND_AUDIT_LOG(refund_id, create_time);
CREATE INDEX IDX_LIBRARY_USER_STATUS ON PLAYER_LIBRARY(user_id, status);
CREATE INDEX IDX_LIBRARY_GAME ON PLAYER_LIBRARY(game_id);
CREATE INDEX IDX_CDKEY_BATCH ON CDKEY(batch_id);
CREATE INDEX IDX_REDEEM_USER_TIME ON CDKEY_REDEEM_LOG(user_id, create_time);
CREATE INDEX IDX_REDEEM_IP_TIME ON CDKEY_REDEEM_LOG(ip_hash, create_time);
CREATE INDEX IDX_REVIEW_GAME_STATUS ON GAME_REVIEW(game_id, status);
CREATE INDEX IDX_ACH_GAME ON ACHIEVEMENT(game_id);
CREATE INDEX IDX_PLAYER_ACH_USER ON PLAYER_ACHIEVEMENT(user_id);
CREATE INDEX IDX_ITEM_TEMPLATE_GAME ON ITEM_TEMPLATE(game_id);
CREATE INDEX IDX_INV_USER_STATUS ON INVENTORY_ITEM(user_id, status);
CREATE INDEX IDX_INV_TEMPLATE_STATUS ON INVENTORY_ITEM(template_id, status);
CREATE INDEX IDX_MARKET_TEMPLATE_STATUS ON MARKET_ORDER(template_id, status, order_type, target_price);
CREATE INDEX IDX_MARKET_USER_STATUS ON MARKET_ORDER(user_id, status);
CREATE UNIQUE INDEX UK_MARKET_ACTIVE_SELL_ITEM ON MARKET_ORDER (
  CASE WHEN order_type = 'SELL' AND status = 'MATCHING' THEN item_id END
);
CREATE INDEX IDX_TRADE_TEMPLATE_TIME ON MARKET_TRADE(template_id, trade_time);
CREATE INDEX IDX_TRADE_BUYER_TIME ON MARKET_TRADE(buyer_id, trade_time);
CREATE INDEX IDX_TRADE_SELLER_TIME ON MARKET_TRADE(seller_id, trade_time);
CREATE INDEX IDX_TRANSFER_ITEM_TIME ON ITEM_TRANSFER_LEDGER(item_id, transfer_time);
CREATE INDEX IDX_TRANSFER_TO_TIME ON ITEM_TRANSFER_LEDGER(to_user_id, transfer_time);

PROMPT Steam course database schema created.
