ALTER TABLE PAYMENT_TRANSACTION ADD (
  payment_method VARCHAR2(20) DEFAULT 'STEAM_WALLET' NOT NULL
);

ALTER TABLE PAYMENT_TRANSACTION ADD CONSTRAINT CK_PAYMENT_METHOD
  CHECK (payment_method IN ('STEAM_WALLET', 'WECHAT_PAY', 'ALIPAY', 'VISA', 'MASTERCARD'));

ALTER TABLE WALLET_TRANSACTION ADD (
  payment_method VARCHAR2(20) DEFAULT 'STEAM_WALLET' NOT NULL
);

ALTER TABLE WALLET_TRANSACTION ADD CONSTRAINT CK_WALLET_TXN_PAYMENT_METHOD
  CHECK (payment_method IN ('STEAM_WALLET', 'WECHAT_PAY', 'ALIPAY', 'VISA', 'MASTERCARD'));

COMMIT;
