SET DEFINE OFF

PROMPT Creating profile, badge, trade-offer, activity, and discussion tables...

DECLARE
  PROCEDURE ensure_table(p_name VARCHAR2, p_sql VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = p_name;
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_sql;
    END IF;
  END;
BEGIN
  ensure_table('PLAYER_PROFILE', q'[
    CREATE TABLE PLAYER_PROFILE (
      user_id VARCHAR2(32) NOT NULL, headline VARCHAR2(120), bio CLOB,
      avatar_key VARCHAR2(40) DEFAULT 'AVATAR_BLUE' NOT NULL,
      background_key VARCHAR2(40) DEFAULT 'BACKGROUND_CS2' NOT NULL,
      theme_key VARCHAR2(30) DEFAULT 'STEAM_BLUE' NOT NULL,
      showcase_game_id VARCHAR2(32), profile_visibility VARCHAR2(20) DEFAULT 'PUBLIC' NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_PLAYER_PROFILE PRIMARY KEY (user_id),
      CONSTRAINT FK_PROFILE_PLAYER FOREIGN KEY (user_id) REFERENCES PLAYER(user_id),
      CONSTRAINT FK_PROFILE_SHOWCASE_GAME FOREIGN KEY (showcase_game_id) REFERENCES GAME(game_id),
      CONSTRAINT CK_PROFILE_AVATAR CHECK (avatar_key IN ('AVATAR_BLUE', 'AVATAR_ORANGE', 'AVATAR_GREEN', 'AVATAR_PURPLE')),
      CONSTRAINT CK_PROFILE_BACKGROUND CHECK (background_key IN ('BACKGROUND_CS2', 'BACKGROUND_DST', 'BACKGROUND_LIBRARY')),
      CONSTRAINT CK_PROFILE_THEME CHECK (theme_key IN ('STEAM_BLUE', 'TACTICAL_ORANGE', 'SURVIVAL_GREEN')),
      CONSTRAINT CK_PROFILE_VISIBILITY CHECK (profile_visibility IN ('PUBLIC', 'FRIENDS', 'PRIVATE'))
    )]');

  ensure_table('BADGE_CATALOG', q'[
    CREATE TABLE BADGE_CATALOG (
      badge_id VARCHAR2(32) NOT NULL, badge_name VARCHAR2(100) NOT NULL,
      description VARCHAR2(500) NOT NULL, icon_key VARCHAR2(40) NOT NULL,
      xp_value NUMBER(5) DEFAULT 0 NOT NULL, rarity VARCHAR2(20) DEFAULT 'COMMON' NOT NULL,
      CONSTRAINT PK_BADGE_CATALOG PRIMARY KEY (badge_id),
      CONSTRAINT CK_BADGE_XP CHECK (xp_value >= 0),
      CONSTRAINT CK_BADGE_RARITY CHECK (rarity IN ('COMMON', 'RARE', 'EPIC'))
    )]');

  ensure_table('PLAYER_BADGE', q'[
    CREATE TABLE PLAYER_BADGE (
      user_id VARCHAR2(32) NOT NULL, badge_id VARCHAR2(32) NOT NULL,
      earned_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, is_featured NUMBER(1) DEFAULT 0 NOT NULL,
      CONSTRAINT PK_PLAYER_BADGE PRIMARY KEY (user_id, badge_id),
      CONSTRAINT FK_PLAYER_BADGE_PLAYER FOREIGN KEY (user_id) REFERENCES PLAYER(user_id),
      CONSTRAINT FK_PLAYER_BADGE_CATALOG FOREIGN KEY (badge_id) REFERENCES BADGE_CATALOG(badge_id),
      CONSTRAINT CK_PLAYER_BADGE_FEATURED CHECK (is_featured IN (0, 1))
    )]');

  ensure_table('TRADE_OFFER', q'[
    CREATE TABLE TRADE_OFFER (
      offer_id VARCHAR2(32) NOT NULL, sender_id VARCHAR2(32) NOT NULL,
      recipient_id VARCHAR2(32) NOT NULL, message VARCHAR2(500),
      status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      responded_at TIMESTAMP, version NUMBER(20) DEFAULT 0 NOT NULL,
      CONSTRAINT PK_TRADE_OFFER PRIMARY KEY (offer_id),
      CONSTRAINT FK_TRADE_OFFER_SENDER FOREIGN KEY (sender_id) REFERENCES PLAYER(user_id),
      CONSTRAINT FK_TRADE_OFFER_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES PLAYER(user_id),
      CONSTRAINT CK_TRADE_OFFER_PARTIES CHECK (sender_id <> recipient_id),
      CONSTRAINT CK_TRADE_OFFER_STATUS CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELED', 'EXPIRED'))
    )]');

  ensure_table('TRADE_OFFER_ITEM', q'[
    CREATE TABLE TRADE_OFFER_ITEM (
      offer_id VARCHAR2(32) NOT NULL, item_id VARCHAR2(32) NOT NULL,
      item_role VARCHAR2(20) NOT NULL, owner_id_at_create VARCHAR2(32) NOT NULL,
      CONSTRAINT PK_TRADE_OFFER_ITEM PRIMARY KEY (offer_id, item_id),
      CONSTRAINT FK_OFFER_ITEM_OFFER FOREIGN KEY (offer_id) REFERENCES TRADE_OFFER(offer_id),
      CONSTRAINT FK_OFFER_ITEM_INVENTORY FOREIGN KEY (item_id) REFERENCES INVENTORY_ITEM(item_id),
      CONSTRAINT FK_OFFER_ITEM_OWNER FOREIGN KEY (owner_id_at_create) REFERENCES PLAYER(user_id),
      CONSTRAINT CK_TRADE_OFFER_ITEM_ROLE CHECK (item_role IN ('OFFERED', 'REQUESTED'))
    )]');

  ensure_table('COMMUNITY_POST', q'[
    CREATE TABLE COMMUNITY_POST (
      post_id VARCHAR2(32) NOT NULL, author_id VARCHAR2(32) NOT NULL, game_id VARCHAR2(32),
      post_type VARCHAR2(20) DEFAULT 'STATUS' NOT NULL, content CLOB NOT NULL,
      media_url VARCHAR2(255), visibility VARCHAR2(20) DEFAULT 'PUBLIC' NOT NULL,
      status VARCHAR2(20) DEFAULT 'VISIBLE' NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_COMMUNITY_POST PRIMARY KEY (post_id),
      CONSTRAINT FK_COMMUNITY_POST_AUTHOR FOREIGN KEY (author_id) REFERENCES PLAYER(user_id),
      CONSTRAINT FK_COMMUNITY_POST_GAME FOREIGN KEY (game_id) REFERENCES GAME(game_id),
      CONSTRAINT CK_COMMUNITY_POST_TYPE CHECK (post_type IN ('STATUS', 'ACHIEVEMENT', 'SCREENSHOT', 'TRADE')),
      CONSTRAINT CK_COMMUNITY_POST_VISIBILITY CHECK (visibility IN ('PUBLIC', 'FRIENDS')),
      CONSTRAINT CK_COMMUNITY_POST_STATUS CHECK (status IN ('VISIBLE', 'HIDDEN', 'DELETED'))
    )]');

  ensure_table('COMMUNITY_POST_REACTION', q'[
    CREATE TABLE COMMUNITY_POST_REACTION (
      post_id VARCHAR2(32) NOT NULL, user_id VARCHAR2(32) NOT NULL,
      reaction_type VARCHAR2(20) DEFAULT 'LIKE' NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_COMMUNITY_POST_REACTION PRIMARY KEY (post_id, user_id),
      CONSTRAINT FK_POST_REACTION_POST FOREIGN KEY (post_id) REFERENCES COMMUNITY_POST(post_id),
      CONSTRAINT FK_POST_REACTION_PLAYER FOREIGN KEY (user_id) REFERENCES PLAYER(user_id),
      CONSTRAINT CK_POST_REACTION_TYPE CHECK (reaction_type IN ('LIKE', 'AWARD'))
    )]');

  ensure_table('DISCUSSION_TOPIC', q'[
    CREATE TABLE DISCUSSION_TOPIC (
      topic_id VARCHAR2(32) NOT NULL, game_id VARCHAR2(32) NOT NULL, author_id VARCHAR2(32) NOT NULL,
      title VARCHAR2(160) NOT NULL, body CLOB NOT NULL, status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_DISCUSSION_TOPIC PRIMARY KEY (topic_id),
      CONSTRAINT FK_DISCUSSION_TOPIC_GAME FOREIGN KEY (game_id) REFERENCES GAME(game_id),
      CONSTRAINT FK_DISCUSSION_TOPIC_AUTHOR FOREIGN KEY (author_id) REFERENCES PLAYER(user_id),
      CONSTRAINT CK_DISCUSSION_TOPIC_STATUS CHECK (status IN ('OPEN', 'LOCKED', 'HIDDEN'))
    )]');

  ensure_table('DISCUSSION_REPLY', q'[
    CREATE TABLE DISCUSSION_REPLY (
      reply_id VARCHAR2(32) NOT NULL, topic_id VARCHAR2(32) NOT NULL, author_id VARCHAR2(32) NOT NULL,
      body CLOB NOT NULL, status VARCHAR2(20) DEFAULT 'VISIBLE' NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_DISCUSSION_REPLY PRIMARY KEY (reply_id),
      CONSTRAINT FK_DISCUSSION_REPLY_TOPIC FOREIGN KEY (topic_id) REFERENCES DISCUSSION_TOPIC(topic_id),
      CONSTRAINT FK_DISCUSSION_REPLY_AUTHOR FOREIGN KEY (author_id) REFERENCES PLAYER(user_id),
      CONSTRAINT CK_DISCUSSION_REPLY_STATUS CHECK (status IN ('VISIBLE', 'DELETED'))
    )]');
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints
   WHERE constraint_name = 'CK_USER_NOTIFICATION_TYPE' AND table_name = 'USER_NOTIFICATION';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE USER_NOTIFICATION DROP CONSTRAINT CK_USER_NOTIFICATION_TYPE';
  END IF;
  EXECUTE IMMEDIATE q'[ALTER TABLE USER_NOTIFICATION ADD CONSTRAINT CK_USER_NOTIFICATION_TYPE CHECK (notification_type IN ('FRIEND_REQUEST', 'FRIEND_ACCEPTED', 'DIRECT_MESSAGE', 'REVIEW_REACTION', 'WORKSHOP_UPDATE', 'TRADE_OFFER', 'COMMUNITY_REPLY', 'BADGE_EARNED', 'SYSTEM'))]';
END;
/

DECLARE
  PROCEDURE ensure_index(p_name VARCHAR2, p_sql VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = p_name;
    IF v_count = 0 THEN EXECUTE IMMEDIATE p_sql; END IF;
  END;
BEGIN
  ensure_index('IDX_PLAYER_BADGE_FEATURED', 'CREATE INDEX IDX_PLAYER_BADGE_FEATURED ON PLAYER_BADGE(user_id, is_featured)');
  ensure_index('IDX_TRADE_OFFER_SENDER_STATUS', 'CREATE INDEX IDX_TRADE_OFFER_SENDER_STATUS ON TRADE_OFFER(sender_id, status, created_at)');
  ensure_index('IDX_TRADE_OFFER_RECIP_STATUS', 'CREATE INDEX IDX_TRADE_OFFER_RECIP_STATUS ON TRADE_OFFER(recipient_id, status, created_at)');
  ensure_index('IDX_TRADE_OFFER_ITEM_ITEM', 'CREATE INDEX IDX_TRADE_OFFER_ITEM_ITEM ON TRADE_OFFER_ITEM(item_id, offer_id)');
  ensure_index('IDX_COMMUNITY_POST_GAME_TIME', 'CREATE INDEX IDX_COMMUNITY_POST_GAME_TIME ON COMMUNITY_POST(game_id, status, created_at)');
  ensure_index('IDX_COMMUNITY_POST_AUTHOR_TIME', 'CREATE INDEX IDX_COMMUNITY_POST_AUTHOR_TIME ON COMMUNITY_POST(author_id, status, created_at)');
  ensure_index('IDX_POST_REACTION_USER', 'CREATE INDEX IDX_POST_REACTION_USER ON COMMUNITY_POST_REACTION(user_id, created_at)');
  ensure_index('IDX_DISCUSSION_GAME_TIME', 'CREATE INDEX IDX_DISCUSSION_GAME_TIME ON DISCUSSION_TOPIC(game_id, status, updated_at)');
  ensure_index('IDX_DISCUSSION_REPLY_TOPIC', 'CREATE INDEX IDX_DISCUSSION_REPLY_TOPIC ON DISCUSSION_REPLY(topic_id, status, created_at)');
END;
/

COMMIT;

PROMPT Community engagement expansion is ready.
